apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ .Chart.Name }}
spec:
{{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ .Values.tls.secretname }}
{{- end }}
  rules:
    - host: {{ .Values.environment }}.{{ .Values.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Chart.Name }}
              servicePort: {{ .Values.grpc_port }}
