// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/todo.proto

package pb // import "github.com/akhilesharora/todo/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_81d116cf27162f17, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Note struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Comments             string   `protobuf:"bytes,3,opt,name=comments,proto3" json:"comments,omitempty"`
	DueDate              string   `protobuf:"bytes,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Note) Reset()         { *m = Note{} }
func (m *Note) String() string { return proto.CompactTextString(m) }
func (*Note) ProtoMessage()    {}
func (*Note) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_81d116cf27162f17, []int{1}
}
func (m *Note) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Note.Unmarshal(m, b)
}
func (m *Note) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Note.Marshal(b, m, deterministic)
}
func (dst *Note) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Note.Merge(dst, src)
}
func (m *Note) XXX_Size() int {
	return xxx_messageInfo_Note.Size(m)
}
func (m *Note) XXX_DiscardUnknown() {
	xxx_messageInfo_Note.DiscardUnknown(m)
}

var xxx_messageInfo_Note proto.InternalMessageInfo

func (m *Note) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Note) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Note) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

func (m *Note) GetDueDate() string {
	if m != nil {
		return m.DueDate
	}
	return ""
}

type GetNoteMsg struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNoteMsg) Reset()         { *m = GetNoteMsg{} }
func (m *GetNoteMsg) String() string { return proto.CompactTextString(m) }
func (*GetNoteMsg) ProtoMessage()    {}
func (*GetNoteMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_81d116cf27162f17, []int{2}
}
func (m *GetNoteMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNoteMsg.Unmarshal(m, b)
}
func (m *GetNoteMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNoteMsg.Marshal(b, m, deterministic)
}
func (dst *GetNoteMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNoteMsg.Merge(dst, src)
}
func (m *GetNoteMsg) XXX_Size() int {
	return xxx_messageInfo_GetNoteMsg.Size(m)
}
func (m *GetNoteMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNoteMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GetNoteMsg proto.InternalMessageInfo

func (m *GetNoteMsg) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetNoteReply struct {
	Note                 *Note    `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNoteReply) Reset()         { *m = GetNoteReply{} }
func (m *GetNoteReply) String() string { return proto.CompactTextString(m) }
func (*GetNoteReply) ProtoMessage()    {}
func (*GetNoteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_81d116cf27162f17, []int{3}
}
func (m *GetNoteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNoteReply.Unmarshal(m, b)
}
func (m *GetNoteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNoteReply.Marshal(b, m, deterministic)
}
func (dst *GetNoteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNoteReply.Merge(dst, src)
}
func (m *GetNoteReply) XXX_Size() int {
	return xxx_messageInfo_GetNoteReply.Size(m)
}
func (m *GetNoteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNoteReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetNoteReply proto.InternalMessageInfo

func (m *GetNoteReply) GetNote() *Note {
	if m != nil {
		return m.Note
	}
	return nil
}

type GetAllNotesReply struct {
	Notes                []*Note  `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllNotesReply) Reset()         { *m = GetAllNotesReply{} }
func (m *GetAllNotesReply) String() string { return proto.CompactTextString(m) }
func (*GetAllNotesReply) ProtoMessage()    {}
func (*GetAllNotesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_81d116cf27162f17, []int{4}
}
func (m *GetAllNotesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllNotesReply.Unmarshal(m, b)
}
func (m *GetAllNotesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllNotesReply.Marshal(b, m, deterministic)
}
func (dst *GetAllNotesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllNotesReply.Merge(dst, src)
}
func (m *GetAllNotesReply) XXX_Size() int {
	return xxx_messageInfo_GetAllNotesReply.Size(m)
}
func (m *GetAllNotesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllNotesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllNotesReply proto.InternalMessageInfo

func (m *GetAllNotesReply) GetNotes() []*Note {
	if m != nil {
		return m.Notes
	}
	return nil
}

type CreateNoteMsg struct {
	Note                 *Note    `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNoteMsg) Reset()         { *m = CreateNoteMsg{} }
func (m *CreateNoteMsg) String() string { return proto.CompactTextString(m) }
func (*CreateNoteMsg) ProtoMessage()    {}
func (*CreateNoteMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_81d116cf27162f17, []int{5}
}
func (m *CreateNoteMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNoteMsg.Unmarshal(m, b)
}
func (m *CreateNoteMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNoteMsg.Marshal(b, m, deterministic)
}
func (dst *CreateNoteMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNoteMsg.Merge(dst, src)
}
func (m *CreateNoteMsg) XXX_Size() int {
	return xxx_messageInfo_CreateNoteMsg.Size(m)
}
func (m *CreateNoteMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNoteMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNoteMsg proto.InternalMessageInfo

func (m *CreateNoteMsg) GetNote() *Note {
	if m != nil {
		return m.Note
	}
	return nil
}

type UpdateNoteMsg struct {
	Note                 *Note    `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNoteMsg) Reset()         { *m = UpdateNoteMsg{} }
func (m *UpdateNoteMsg) String() string { return proto.CompactTextString(m) }
func (*UpdateNoteMsg) ProtoMessage()    {}
func (*UpdateNoteMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_81d116cf27162f17, []int{6}
}
func (m *UpdateNoteMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNoteMsg.Unmarshal(m, b)
}
func (m *UpdateNoteMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNoteMsg.Marshal(b, m, deterministic)
}
func (dst *UpdateNoteMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNoteMsg.Merge(dst, src)
}
func (m *UpdateNoteMsg) XXX_Size() int {
	return xxx_messageInfo_UpdateNoteMsg.Size(m)
}
func (m *UpdateNoteMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNoteMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNoteMsg proto.InternalMessageInfo

func (m *UpdateNoteMsg) GetNote() *Note {
	if m != nil {
		return m.Note
	}
	return nil
}

type UpdateNoteReply struct {
	Note                 *Note    `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNoteReply) Reset()         { *m = UpdateNoteReply{} }
func (m *UpdateNoteReply) String() string { return proto.CompactTextString(m) }
func (*UpdateNoteReply) ProtoMessage()    {}
func (*UpdateNoteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_81d116cf27162f17, []int{7}
}
func (m *UpdateNoteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNoteReply.Unmarshal(m, b)
}
func (m *UpdateNoteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNoteReply.Marshal(b, m, deterministic)
}
func (dst *UpdateNoteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNoteReply.Merge(dst, src)
}
func (m *UpdateNoteReply) XXX_Size() int {
	return xxx_messageInfo_UpdateNoteReply.Size(m)
}
func (m *UpdateNoteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNoteReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNoteReply proto.InternalMessageInfo

func (m *UpdateNoteReply) GetNote() *Note {
	if m != nil {
		return m.Note
	}
	return nil
}

type DeleteNoteMsg struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNoteMsg) Reset()         { *m = DeleteNoteMsg{} }
func (m *DeleteNoteMsg) String() string { return proto.CompactTextString(m) }
func (*DeleteNoteMsg) ProtoMessage()    {}
func (*DeleteNoteMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_81d116cf27162f17, []int{8}
}
func (m *DeleteNoteMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNoteMsg.Unmarshal(m, b)
}
func (m *DeleteNoteMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNoteMsg.Marshal(b, m, deterministic)
}
func (dst *DeleteNoteMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNoteMsg.Merge(dst, src)
}
func (m *DeleteNoteMsg) XXX_Size() int {
	return xxx_messageInfo_DeleteNoteMsg.Size(m)
}
func (m *DeleteNoteMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNoteMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNoteMsg proto.InternalMessageInfo

func (m *DeleteNoteMsg) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "todo.Empty")
	proto.RegisterType((*Note)(nil), "todo.Note")
	proto.RegisterType((*GetNoteMsg)(nil), "todo.GetNoteMsg")
	proto.RegisterType((*GetNoteReply)(nil), "todo.GetNoteReply")
	proto.RegisterType((*GetAllNotesReply)(nil), "todo.GetAllNotesReply")
	proto.RegisterType((*CreateNoteMsg)(nil), "todo.CreateNoteMsg")
	proto.RegisterType((*UpdateNoteMsg)(nil), "todo.UpdateNoteMsg")
	proto.RegisterType((*UpdateNoteReply)(nil), "todo.UpdateNoteReply")
	proto.RegisterType((*DeleteNoteMsg)(nil), "todo.DeleteNoteMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoClient is the client API for Todo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoClient interface {
	CreateNote(ctx context.Context, in *CreateNoteMsg, opts ...grpc.CallOption) (*Empty, error)
	UpdateNote(ctx context.Context, in *UpdateNoteMsg, opts ...grpc.CallOption) (*UpdateNoteReply, error)
	DeleteNote(ctx context.Context, in *DeleteNoteMsg, opts ...grpc.CallOption) (*Empty, error)
	GetAllNotes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllNotesReply, error)
}

type todoClient struct {
	cc *grpc.ClientConn
}

func NewTodoClient(cc *grpc.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) CreateNote(ctx context.Context, in *CreateNoteMsg, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/todo.Todo/CreateNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) UpdateNote(ctx context.Context, in *UpdateNoteMsg, opts ...grpc.CallOption) (*UpdateNoteReply, error) {
	out := new(UpdateNoteReply)
	err := c.cc.Invoke(ctx, "/todo.Todo/UpdateNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) DeleteNote(ctx context.Context, in *DeleteNoteMsg, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/todo.Todo/DeleteNote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) GetAllNotes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllNotesReply, error) {
	out := new(GetAllNotesReply)
	err := c.cc.Invoke(ctx, "/todo.Todo/GetAllNotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServer is the server API for Todo service.
type TodoServer interface {
	CreateNote(context.Context, *CreateNoteMsg) (*Empty, error)
	UpdateNote(context.Context, *UpdateNoteMsg) (*UpdateNoteReply, error)
	DeleteNote(context.Context, *DeleteNoteMsg) (*Empty, error)
	GetAllNotes(context.Context, *Empty) (*GetAllNotesReply, error)
}

func RegisterTodoServer(s *grpc.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNoteMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Todo/CreateNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).CreateNote(ctx, req.(*CreateNoteMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_UpdateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNoteMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).UpdateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Todo/UpdateNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).UpdateNote(ctx, req.(*UpdateNoteMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_DeleteNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNoteMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).DeleteNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Todo/DeleteNote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).DeleteNote(ctx, req.(*DeleteNoteMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_GetAllNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetAllNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todo.Todo/GetAllNotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetAllNotes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todo.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNote",
			Handler:    _Todo_CreateNote_Handler,
		},
		{
			MethodName: "UpdateNote",
			Handler:    _Todo_UpdateNote_Handler,
		},
		{
			MethodName: "DeleteNote",
			Handler:    _Todo_DeleteNote_Handler,
		},
		{
			MethodName: "GetAllNotes",
			Handler:    _Todo_GetAllNotes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/todo.proto",
}

func init() { proto.RegisterFile("pb/todo.proto", fileDescriptor_todo_81d116cf27162f17) }

var fileDescriptor_todo_81d116cf27162f17 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xa5, 0x50, 0x04, 0x07, 0xab, 0x66, 0xfd, 0x48, 0x6d, 0x8c, 0x36, 0x7b, 0xe2, 0xd4, 0x2a,
	0x72, 0xf2, 0xa6, 0x62, 0x38, 0xe9, 0x81, 0xe8, 0xc5, 0x8b, 0x69, 0xd9, 0x09, 0x34, 0xb6, 0x6c,
	0xd3, 0x0e, 0x07, 0xfe, 0xab, 0x3f, 0xc6, 0x74, 0x57, 0x2c, 0xec, 0x45, 0xbd, 0xed, 0xbc, 0xb7,
	0x6f, 0xdf, 0x9b, 0x9d, 0x01, 0x27, 0x8f, 0x43, 0x92, 0x42, 0x06, 0x79, 0x21, 0x49, 0x32, 0xbb,
	0x3a, 0xf3, 0x0e, 0xb4, 0x1f, 0xb3, 0x9c, 0x56, 0x7c, 0x0a, 0xf6, 0xb3, 0x24, 0x64, 0xfb, 0xd0,
	0x4c, 0x84, 0x6b, 0xf9, 0x56, 0xdf, 0x99, 0x34, 0x13, 0xc1, 0x8e, 0xa1, 0x4d, 0x09, 0xa5, 0xe8,
	0x36, 0x7d, 0xab, 0xbf, 0x3b, 0xd1, 0x05, 0xf3, 0xa0, 0x3b, 0x95, 0x59, 0x86, 0x0b, 0x2a, 0xdd,
	0x96, 0x22, 0x7e, 0x6a, 0x76, 0x06, 0x5d, 0xb1, 0xc4, 0x77, 0x11, 0x11, 0xba, 0xb6, 0xe2, 0x3a,
	0x62, 0x89, 0xa3, 0x88, 0x90, 0x9f, 0x03, 0x8c, 0x91, 0x2a, 0x9f, 0xa7, 0x72, 0x66, 0x5a, 0xf1,
	0x00, 0xf6, 0xbe, 0xd9, 0x09, 0xe6, 0xe9, 0x8a, 0x5d, 0x80, 0xbd, 0x90, 0x84, 0xea, 0x46, 0x6f,
	0x00, 0x81, 0x0a, 0xaf, 0x68, 0x85, 0xf3, 0x21, 0x1c, 0x8e, 0x91, 0xee, 0xd2, 0xb4, 0xc2, 0x4a,
	0xad, 0xf1, 0xa1, 0x5d, 0x71, 0xa5, 0x6b, 0xf9, 0x2d, 0x43, 0xa4, 0x09, 0x1e, 0x82, 0xf3, 0x50,
	0x60, 0x44, 0xb8, 0x8e, 0xf1, 0x9b, 0x4d, 0x08, 0xce, 0x6b, 0x2e, 0xfe, 0x21, 0xb8, 0x86, 0x83,
	0x5a, 0xf0, 0xb7, 0x56, 0x2e, 0xc1, 0x19, 0x61, 0x8a, 0xb5, 0x87, 0xf1, 0x37, 0x83, 0x4f, 0x0b,
	0xec, 0x17, 0x29, 0x24, 0xbb, 0x02, 0xa8, 0xe3, 0xb3, 0x23, 0xfd, 0xd2, 0x56, 0x43, 0x5e, 0x4f,
	0x83, 0x7a, 0xae, 0x0d, 0x76, 0x0b, 0x50, 0xc7, 0x59, 0x2b, 0xb6, 0x3a, 0xf2, 0x4e, 0x4c, 0x50,
	0xa5, 0xe6, 0x8d, 0xca, 0xad, 0xce, 0xb5, 0xd6, 0x6e, 0x25, 0x35, 0xdd, 0x86, 0xd0, 0xdb, 0x18,
	0x0a, 0xdb, 0x64, 0xbd, 0x53, 0x5d, 0x98, 0x43, 0xe3, 0x8d, 0x7b, 0xfe, 0xe6, 0xcf, 0x12, 0x9a,
	0x2f, 0xe3, 0x60, 0x2a, 0xb3, 0x30, 0xfa, 0x98, 0x27, 0x29, 0x96, 0xf3, 0xa8, 0x90, 0x45, 0xa4,
	0x76, 0x36, 0xcc, 0xe3, 0x78, 0x47, 0xed, 0xed, 0xcd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6e,
	0xc0, 0xb3, 0x0d, 0xc8, 0x02, 0x00, 0x00,
}
